### ISSUE TITLE
read pls

### ISSUE THREAD

**Issue by agiloooo** [Chaxiraxi/Discord-Token-Grabber#3]
why the email and token is my token and the email is my email why? i want to grab a scammers token

**Comment by Chaxiraxi** [comment]
Hi, it's because the script is made to hack the current account which is logged in in the current browser where the JavaScript code is executed. To hack scammers, you have to use some social Engerinering attacks vector to makes them executing the code, and get their tokens hacked. This is not a magic script that will hack easily any Discord account. If it worked like this, the security will be a complete mess.
